(function(){"use strict";
const C=window.DPRO_TUTORIAL_CONTENT; if(!C||!Array.isArray(C.first10)||C.first10.length!==10){document.body.textContent="Tutorial content error";return;}
const $=s=>document.querySelector(s), frame=$("#tutorialFrame"), card=$("#tutorialCard"), handle=$("#dragHandle"), hi=$("#targetHighlight");
const E={stepLabel:$("#stepLabel"),role:$("#roleLabel"),title:$("#stepTitle"),body:$("#stepBody"),fallback:$("#fallbackBox"),progress:$("#progressBar"),back:$("#backButton"),next:$("#nextButton"),skip:$("#skipButton"),close:$("#closeButton"),resume:$("#resumeButton"),replay:$("#replayButton")};
const KEY="dpro_tutorial_houkago_v11"; const POSKEY="dpro_tutorial_houkago_card_pos_v11"; const SAFE_ROLES={public_demo:"公開デモ",guardian_contact:"保護者連絡",guardian_member:"保護者マイページ",staff:"スタッフiPad",owner_admin:"管理PC"};
let state={index:0,closed:false,complete:false}; let drag=null; let target=null; let raf=0;
function read(){try{const x=JSON.parse(localStorage.getItem(KEY)||"null");if(x&&Number.isInteger(x.index))state={index:Math.max(0,Math.min(9,x.index)),closed:!!x.closed,complete:!!x.complete};}catch(_){}}
function save(){localStorage.setItem(KEY,JSON.stringify({index:state.index,closed:state.closed,complete:state.complete}));}
function routePath(route){return String(route||"").split("?")[0].replace(/^\.\//,"");}
function framePath(){try{return (frame.contentWindow.location.pathname.split('/').pop()||'')+(frame.contentWindow.location.search||'');}catch(_){return '';}}
function routeMatches(step){return framePath().startsWith(routePath(step.route));}
function visible(el){if(!el)return false; const s=frame.contentWindow.getComputedStyle(el); if(s.display==='none'||s.visibility==='hidden'||Number(s.opacity)===0)return false; const r=el.getBoundingClientRect(); return r.width>2&&r.height>2;}
function findTarget(step){try{const d=frame.contentDocument; for(const sel of step.target_selectors||[]){const els=Array.from(d.querySelectorAll(sel));const v=els.find(visible);if(v)return v;} }catch(_){} return null;}
function clearHighlight(){target=null;hi.dataset.visible="false";}
function placeHighlight(){if(!target||!visible(target)){clearHighlight();return;} const fr=frame.getBoundingClientRect(),r=target.getBoundingClientRect(); const pad=5; const x=Math.max(3,fr.left+r.left-pad), y=Math.max(3,fr.top+r.top-pad), w=Math.min(innerWidth-x-3,r.width+pad*2), h=Math.min(innerHeight-y-3,r.height+pad*2); Object.assign(hi.style,{left:x+'px',top:y+'px',width:Math.max(8,w)+'px',height:Math.max(8,h)+'px'}); hi.dataset.visible="true";}
function watchHighlight(){cancelAnimationFrame(raf); const loop=()=>{placeHighlight();raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);}
function clampCard(){const r=card.getBoundingClientRect(),m=6,maxX=Math.max(m,innerWidth-r.width-m),maxY=Math.max(m,innerHeight-r.height-m);let left=Math.min(maxX,Math.max(m,r.left)),top=Math.min(maxY,Math.max(m,r.top));card.style.left=left+'px';card.style.top=top+'px'; localStorage.setItem(POSKEY,JSON.stringify({left,top}));}
function restorePos(){try{const p=JSON.parse(localStorage.getItem(POSKEY)||'null');if(p&&Number.isFinite(p.left)&&Number.isFinite(p.top)){card.style.left=p.left+'px';card.style.top=p.top+'px';}}catch(_){} requestAnimationFrame(clampCard);}
function step(){return C.first10[state.index];}
function renderText(fallback){const s=step();E.stepLabel.textContent=`STEP ${s.step} / 10`;E.role.textContent=SAFE_ROLES[s.role]||s.role;E.title.textContent=s.title;E.body.textContent=s.body;E.progress.style.width=`${s.step*10}%`;E.back.disabled=state.index===0;E.next.textContent=state.index===9?'完了':'次へ';E.fallback.hidden=!fallback;E.fallback.textContent=fallback?s.fallback:'';}
function loadStep(force){const s=step(); state.closed=false;state.complete=false;save();card.hidden=false;E.resume.hidden=true;renderText(false);clearHighlight(); const wanted=s.route; if(force||!routeMatches(s)){frame.src='./'+wanted;return;} bindTarget();}
function bindTarget(){const s=step();target=findTarget(s);renderText(!target);if(target){try{target.scrollIntoView({block:'center',inline:'nearest',behavior:'smooth'});}catch(_){target.scrollIntoView();}setTimeout(placeHighlight,150);}else clearHighlight();watchHighlight();}
function next(){if(state.index>=9){state.complete=true;state.closed=true;save();card.hidden=true;E.resume.hidden=false;E.resume.textContent='操作ガイドをもう一度見る';clearHighlight();toast('First10 を完了しました');return;}state.index++;loadStep(false);}
function back(){if(state.index<=0)return;state.index--;loadStep(false);}
function skip(){state.complete=true;state.closed=true;save();card.hidden=true;E.resume.hidden=false;E.resume.textContent='操作ガイドを再開';clearHighlight();toast('操作ガイドをスキップしました');}
function close(){state.closed=true;save();card.hidden=true;E.resume.hidden=false;E.resume.textContent=state.complete?'操作ガイドをもう一度見る':'操作ガイドを再開';clearHighlight();}
function resume(){if(state.complete){state.index=0;state.complete=false;}state.closed=false;save();card.hidden=false;E.resume.hidden=true;loadStep(false);}
function replay(){state={index:0,closed:false,complete:false};save();card.hidden=false;E.resume.hidden=true;loadStep(true);}
function toast(msg){const d=document.createElement('div');d.className='dt-toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),2200)}
function dragStart(e){if(e.button!==undefined&&e.button!==0)return; if(e.target.closest('button,a,input,select,textarea'))return; const r=card.getBoundingClientRect();drag={id:e.pointerId,x:e.clientX-r.left,y:e.clientY-r.top};handle.setPointerCapture?.(e.pointerId);e.preventDefault();}
function dragMove(e){if(!drag||e.pointerId!==drag.id)return;const r=card.getBoundingClientRect(),m=6,maxX=Math.max(m,innerWidth-r.width-m),maxY=Math.max(m,innerHeight-r.height-m);const left=Math.min(maxX,Math.max(m,e.clientX-drag.x)),top=Math.min(maxY,Math.max(m,e.clientY-drag.y));card.style.left=left+'px';card.style.top=top+'px';e.preventDefault();}
function dragEnd(e){if(!drag||e.pointerId!==drag.id)return;drag=null;clampCard();}
function keyboard(e){if(e.key==='Escape'&&!card.hidden){e.preventDefault();close();return;}if(e.altKey&&e.key==='ArrowRight'){e.preventDefault();next();return;}if(e.altKey&&e.key==='ArrowLeft'){e.preventDefault();back();return;}if(document.activeElement===handle&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const r=card.getBoundingClientRect(),delta=e.shiftKey?40:12;let l=r.left,t=r.top;if(e.key==='ArrowLeft')l-=delta;if(e.key==='ArrowRight')l+=delta;if(e.key==='ArrowUp')t-=delta;if(e.key==='ArrowDown')t+=delta;card.style.left=l+'px';card.style.top=t+'px';clampCard();}}
frame.addEventListener('load',()=>{setTimeout(bindTarget,80)});E.next.addEventListener('click',next);E.back.addEventListener('click',back);E.skip.addEventListener('click',skip);E.close.addEventListener('click',close);E.resume.addEventListener('click',resume);E.replay.addEventListener('click',replay);handle.addEventListener('pointerdown',dragStart);handle.addEventListener('pointermove',dragMove);handle.addEventListener('pointerup',dragEnd);handle.addEventListener('pointercancel',dragEnd);addEventListener('keydown',keyboard);addEventListener('resize',()=>{clampCard();placeHighlight()});
read();const q=new URLSearchParams(location.search);if(q.get('replay')==='1'){state={index:Math.max(0,Math.min(9,Number(q.get('step')||1)-1)),closed:false,complete:false};save();}restorePos();if(state.closed){card.hidden=true;E.resume.hidden=false;E.resume.textContent=state.complete?'操作ガイドをもう一度見る':'操作ガイドを再開';frame.src='./'+step().route;}else loadStep(true);
window.DPRO_TUTORIAL_TEST={content:C,getState:()=>({...state}),clampCard,findTarget:()=>findTarget(step()),next,back,close,resume,replay,skip,routeMatches:()=>routeMatches(step()),bindTarget};
})();
